### PR TITLE
alter table to reflect proposed FAC10 curriculum

### PR DESCRIPTION
**Pull request by SavageWilliam**
I noticed that this needs updating inline with the new curriculum. It's currently accessible via link from '/programme'

Note: the changes I've made need reviewing as I'm not 100% on the final decision on UX week? @bradreeder

### CODE REVIEW

**Comment by bradreeder** [comment]
@SavageWilliam I'm afraid a decision on what week 10 will cover is forthcoming as a bit of debate needs to happen around how we're structuring weeks 10-16 for the next curriculum. https://github.com/foundersandcoders/master-reference/issues/14

I've just changed it to 'Final project' for now as it's what we've done in the past. If you're okay with that let me know and I'm happy to merge.

**Comment by des-des** [comment]
Generally, we need to peg commits against issues, otherwise it is impossible to see where decisions have come from..

**Comment by bradreeder** [comment]
Sorry @des-des , I only intended it as a placeholder decision until we all get to discuss it in detail. Happy to hold off until the discussion around it happens if you think publishing this here would be a bad idea.

**Comment by des-des** [comment]
@bradreeder All fine, when I first looked at this pull I thought it was in the other repo

**Pull request merged**
